service: api-v3-cogs-red

plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline-scheduler
  - serverless-offline

custom:
  cogsTable: 'cogs-table-${self:provider.stage}'
  reposTable: 'repos-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { 'Fn::GetAtt': ['CogsDynamoDBTable', 'Arn'] }
        - { 'Fn::GetAtt': ['ReposDynamoDBTable', 'Arn'] }
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
    - Effect: Allow
      Action:
        - 'secretsmanager:*'
      Resource:
        - ${env:AUTH0_SECRET_ARN}

  environment:
    COGS_TABLE: ${self:custom.cogsTable}
    REPOS_TABLE: ${self:custom.reposTable}
    GITHUB_TOKEN: ${env:GH_TOKEN}
    WH_URL: ${env:WH_URL}

functions:
  - ${file(./src/functions.yml)}

resources:
  Resources:
    SMPermissions:
      Type: 'AWS::Lambda::Permission'
      Properties:
        Principal: secretsmanager.amazonaws.com
        FunctionName: { 'Fn::GetAtt': ['SmLambdaFunction', 'Arn'] }
        Action: 'lambda:InvokeFunction'
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    CogsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: authorName
            AttributeType: S
          - AttributeName: path
            AttributeType: S
        KeySchema:
          - AttributeName: authorName
            KeyType: HASH
          - AttributeName: path
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.cogsTable}
    ReposDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: authorName
            AttributeType: S
          - AttributeName: path
            AttributeType: S
        KeySchema:
          - AttributeName: authorName
            KeyType: HASH
          - AttributeName: path
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.reposTable}
